" Name:         Nonsense
" Description:  Vim colorscheme that doesn't make sense
" Author:       Robertus Diawan Chris <github.com/bruhtus>
" Maintainer:   Robertus Diawan Chris <github.com/bruhtus>
" Website:      https://bruhtus.github.io/
" License:      Public domain
" Last Updated: Thu 07 Oct 2021 10:55:50 AM WIB

" Generated by Colortemplate v2.1.0

set background=dark

hi clear
let g:colors_name = 'nonsense'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Operator Statement
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#121212', '#d75f87', '#afd7af', '#d7af87', '#87afff', '#d7afaf', '#64ffff', '#d0d0d0', '#8a8a8a', '#d78787', '#87d787', '#ffd7af', '#5fafff', '#ffafaf', '#87d7d7', '#eeeeee']
  if get(g:, 'nonsense_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#d0d0d0 guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#d0d0d0 guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#d0d0d0 guibg=#121212 gui=NONE cterm=NONE
    hi Terminal guifg=#d0d0d0 guibg=#121212 gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#8a8a8a gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#8a8a8a gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#8a8a8a gui=NONE cterm=NONE
  hi CursorLineNr guifg=#ffd7af guibg=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#87d787 guibg=#121212 gui=reverse cterm=reverse
  hi DiffChange guifg=#d0d0d0 guibg=#121212 gui=reverse cterm=reverse
  hi DiffDelete guifg=#d75f87 guibg=#d0d0d0 gui=reverse cterm=reverse
  hi DiffText guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Directory guifg=#5fafff guibg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#121212 guibg=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#eeeeee guibg=#d75f87 gui=NONE cterm=NONE
  hi FoldColumn guifg=NONE guibg=#121212 gui=NONE cterm=NONE
  hi Folded guifg=#d0d0d0 guibg=#121212 gui=italic cterm=italic
  hi IncSearch guifg=#d0d0d0 guibg=#121212 gui=standout cterm=reverse
  hi LineNr guifg=#8a8a8a guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=NONE guibg=#8a8a8a gui=NONE cterm=NONE
  hi ModeMsg guifg=#afd7af guibg=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#afd7af guibg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#8a8a8a guibg=NONE gui=NONE cterm=NONE
  hi Number guifg=#ffd7af guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#d7af87 guibg=#121212 gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#ffd7af gui=NONE cterm=NONE
  hi PmenuSel guifg=#d7af87 guibg=#121212 gui=reverse cterm=reverse
  hi PmenuThumb guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Question guifg=#afd7af guibg=NONE gui=NONE cterm=NONE
  hi Search guifg=#87afff guibg=#121212 gui=reverse cterm=reverse
  hi SignColumn guifg=#87afff guibg=#121212 gui=NONE cterm=NONE
  hi SpecialKey guifg=#8a8a8a guibg=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#d75f87 guibg=NONE gui=underline cterm=underline
  hi SpellCap guifg=#5fafff guibg=NONE gui=underline cterm=underline
  hi SpellLocal guifg=#87afff guibg=NONE gui=underline cterm=underline
  hi SpellRare guifg=#ffafaf guibg=NONE gui=underline cterm=underline
  hi StatusLine guifg=#ffd7af guibg=#121212 gui=bold cterm=bold
  hi StatusLineNC guifg=#eeeeee guibg=#121212 gui=NONE cterm=NONE
  hi String guifg=#afd7af guibg=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#d0d0d0 guibg=#121212 gui=NONE cterm=NONE
  hi TabLineFill guifg=#d0d0d0 guibg=#121212 gui=reverse cterm=reverse
  hi TabLineSel guifg=#ffd7af guibg=#121212 gui=NONE cterm=NONE
  hi Title guifg=#d7afaf guibg=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#121212 guibg=#121212 gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#8a8a8a gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#8a8a8a gui=NONE cterm=NONE
  hi WarningMsg guifg=#afd7af guibg=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#ffd7af guibg=#121212 gui=reverse cterm=reverse
  hi Comment guifg=#d7af87 guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#ffd7af guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#eeeeee guibg=#d75f87 gui=NONE cterm=NONE
  hi Identifier guifg=#ffafaf guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#8a8a8a guibg=#8a8a8a gui=NONE cterm=NONE
  hi PreProc guifg=#ffd7af guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#ffafaf guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#87afff guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#d75f87 guibg=NONE gui=NONE cterm=NONE
  hi Type guifg=#d7af87 guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#d7afaf guibg=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=#d0d0d0 gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#121212 gui=NONE cterm=NONE
  hi ToolbarButton guifg=#d0d0d0 guibg=#121212 gui=bold cterm=bold
  hi diffAdded guifg=#afd7af guibg=#121212 gui=NONE cterm=NONE
  hi diffRemove guifg=#d75f87 guibg=#121212 gui=NONE cterm=NONE
  hi diffText guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CommandModeColor guifg=#d75f87 guibg=#121212 gui=reverse cterm=reverse
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'nonsense_transp_bg', 0)
    hi Normal ctermfg=252 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=252 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=252 ctermbg=233 cterm=NONE
    if !has('patch-8.0.0616') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=252 ctermbg=233 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=245 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=245 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=245 cterm=NONE
  hi CursorLineNr ctermfg=223 ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=114 ctermbg=233 cterm=reverse
  hi DiffChange ctermfg=252 ctermbg=233 cterm=reverse
  hi DiffDelete ctermfg=168 ctermbg=252 cterm=reverse
  hi DiffText ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Directory ctermfg=75 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=233 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=255 ctermbg=168 cterm=NONE
  hi FoldColumn ctermfg=NONE ctermbg=233 cterm=NONE
  hi Folded ctermfg=252 ctermbg=233 cterm=italic
  hi IncSearch ctermfg=252 ctermbg=233 cterm=reverse
  hi LineNr ctermfg=245 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=245 cterm=NONE
  hi ModeMsg ctermfg=151 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=151 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=245 ctermbg=NONE cterm=NONE
  hi Number ctermfg=223 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=180 ctermbg=233 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=223 cterm=NONE
  hi PmenuSel ctermfg=180 ctermbg=233 cterm=reverse
  hi PmenuThumb ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Question ctermfg=151 ctermbg=NONE cterm=NONE
  hi Search ctermfg=110 ctermbg=233 cterm=reverse
  hi SignColumn ctermfg=110 ctermbg=233 cterm=NONE
  hi SpecialKey ctermfg=245 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=168 ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=75 ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=110 ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=217 ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=223 ctermbg=233 cterm=bold
  hi StatusLineNC ctermfg=255 ctermbg=233 cterm=NONE
  hi String ctermfg=151 ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=252 ctermbg=233 cterm=NONE
  hi TabLineFill ctermfg=252 ctermbg=233 cterm=reverse
  hi TabLineSel ctermfg=223 ctermbg=233 cterm=NONE
  hi Title ctermfg=181 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=233 ctermbg=233 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=245 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=245 cterm=NONE
  hi WarningMsg ctermfg=151 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=223 ctermbg=233 cterm=reverse
  hi Comment ctermfg=180 ctermbg=NONE cterm=italic
  hi Constant ctermfg=223 ctermbg=NONE cterm=NONE
  hi Error ctermfg=255 ctermbg=168 cterm=NONE
  hi Identifier ctermfg=217 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=245 ctermbg=245 cterm=NONE
  hi PreProc ctermfg=223 ctermbg=NONE cterm=NONE
  hi Special ctermfg=217 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=110 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=168 ctermbg=NONE cterm=NONE
  hi Type ctermfg=180 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=181 ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=252 cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=233 cterm=NONE
  hi ToolbarButton ctermfg=252 ctermbg=233 cterm=bold
  hi diffAdded ctermfg=151 ctermbg=233 cterm=NONE
  hi diffRemove ctermfg=168 ctermbg=233 cterm=NONE
  hi diffText ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CommandModeColor ctermfg=168 ctermbg=233 cterm=reverse
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'nonsense_transp_bg', 0)
    hi Normal ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLineNr ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=LightGreen ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi DiffDelete ctermfg=DarkRed ctermbg=LightGrey cterm=reverse
  hi DiffText ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Directory ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=Black ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=White ctermbg=DarkRed cterm=NONE
  hi FoldColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi Folded ctermfg=LightGrey ctermbg=Black cterm=italic
  hi IncSearch ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi LineNr ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi ModeMsg ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi NonText ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Number ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=DarkYellow ctermbg=Black cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=LightYellow cterm=NONE
  hi PmenuSel ctermfg=DarkYellow ctermbg=Black cterm=reverse
  hi PmenuThumb ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Question ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Search ctermfg=DarkBlue ctermbg=Black cterm=reverse
  hi SignColumn ctermfg=DarkBlue ctermbg=Black cterm=NONE
  hi SpecialKey ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=DarkRed ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=LightBlue ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=DarkBlue ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=LightMagenta ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=LightYellow ctermbg=Black cterm=bold
  hi StatusLineNC ctermfg=White ctermbg=Black cterm=NONE
  hi String ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi TabLineSel ctermfg=LightYellow ctermbg=Black cterm=NONE
  hi Title ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=Black ctermbg=Black cterm=NONE
  hi Visual ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi WarningMsg ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=LightYellow ctermbg=Black cterm=reverse
  hi Comment ctermfg=DarkYellow ctermbg=NONE cterm=italic
  hi Constant ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Error ctermfg=White ctermbg=DarkRed cterm=NONE
  hi Identifier ctermfg=LightMagenta ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=DarkGrey ctermbg=DarkGrey cterm=NONE
  hi PreProc ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Special ctermfg=LightMagenta ctermbg=NONE cterm=NONE
  hi Statement ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Todo ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Type ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=LightGrey ctermbg=Black cterm=bold
  hi diffAdded ctermfg=DarkGreen ctermbg=Black cterm=NONE
  hi diffRemove ctermfg=DarkRed ctermbg=Black cterm=NONE
  hi diffText ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CommandModeColor ctermfg=DarkRed ctermbg=Black cterm=reverse
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black         rgb(18,  18,  18)       233         Black
" Color: red           rgb(215, 95,  135)      168         DarkRed
" Color: green         rgb(175, 215, 175)      151         DarkGreen
" Color: yellow        rgb(215, 175, 135)      180         DarkYellow
" Color: blue          rgb(135, 175, 255)      110         DarkBlue
" Color: magenta       rgb(215, 175, 175)      181         DarkMagenta
" Color: cyan          rgb(100, 255, 255)      109         DarkCyan
" Color: white         rgb(208, 208, 208)      252         LightGrey
" Color: brightblack   rgb(138, 138, 138)      245         DarkGrey
" Color: brightred     rgb(215, 135, 135)      174         LightRed
" Color: brightgreen   rgb(135, 215, 135)      114         LightGreen
" Color: brightyellow  rgb(255, 215, 175)      223         LightYellow
" Color: brightblue    rgb(95,  175, 255)      75          LightBlue
" Color: brightmagenta rgb(255, 175, 175)      217         LightMagenta
" Color: brightcyan    rgb(135, 215, 215)      116         LightCyan
" Color: brightwhite   rgb(238, 238, 238)      255         White
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=2 sw=2
